apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: immich-http
  namespace: {{ include "helpers.namespace" . }}
spec:
  entryPoints:
    - web
  routes:
    - match: "Host(`{{ .Values.externalDomain }}`)"
      kind: Rule
      services:
        - name: {{ .Values.services.server.name }}
          port: {{ .Values.services.server.port }}