apiVersion: /v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ include "helpers.namespace" . }}
type: Opaque
data:
  db-username: {{ .Values.database.user | b64enc | quote }}
  db-password: {{ .Values.database.password | b64enc | quote }}
