kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.services.server.name }}
  namespace: {{ include "helpers.namespace" . }}
spec:
  ports:
  - name: http
    port: {{ .Values.services.server.port }}
  selector:
    app: {{ .Values.services.server.name }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.services.machineLearning.name }}
  namespace: {{ include "helpers.namespace" . }}
spec:
  ports:
  - name: http
    port: {{ .Values.services.machineLearning.port }}
  selector:
    app: {{ .Values.services.machineLearning.name }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.services.redis.name }}
  namespace: {{ include "helpers.namespace" . }}
spec:
  ports:
  - name: redis
    port: {{ .Values.services.redis.port }}
  selector:
    app: {{ .Values.services.redis.name }}
