apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ include "helpers.namespace" . }}
type: Opaque
data:
  password: {{ .Values.login.password | b64enc | quote }}
  user: {{ .Values.login.user | b64enc | quote }}
