kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ include "helpers.namespace" . }}
spec:
  ports:
  - name: postgres
    port: {{ .Values.service.port }}
  selector:
    app: {{ .Values.service.name }}